-- Drop existing tables
DROP TABLE IF EXISTS public.book_user CASCADE;
DROP TABLE IF EXISTS public.books CASCADE;

------------------------ TABLES ----------------------------

-- Books table
CREATE TABLE public.books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  title CHARACTER VARYING NOT NULL,
  author CHARACTER VARYING NULL,
  CONSTRAINT books_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Book-User junction table
CREATE TABLE public.book_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  book_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  status CHARACTER VARYING NOT NULL,
  rating NUMERIC(2,1) NULL,
  page_count BIGINT NULL,
  current_page BIGINT NULL,
  progress BIGINT NULL,
  comment TEXT NULL,
  CONSTRAINT book_user_pkey PRIMARY KEY (id),
  CONSTRAINT book_user_unique UNIQUE (book_id, user_id),
  CONSTRAINT book_user_book_id_fkey FOREIGN KEY (book_id) REFERENCES books (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT book_user_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

------------------------ CONSTRAINTS ----------------------------

ALTER TABLE book_user ADD CONSTRAINT status_check
  CHECK (status IN ('reading', 'want-to-read', 'finished'));

ALTER TABLE book_user ADD CONSTRAINT rating_check
  CHECK (rating BETWEEN 0 AND 5 OR rating IS NULL);

ALTER TABLE book_user ADD CONSTRAINT page_count_check
  CHECK (page_count >= 0 OR page_count IS NULL);

ALTER TABLE book_user ADD CONSTRAINT current_page_check
  CHECK (current_page >= 0 OR current_page IS NULL);

ALTER TABLE book_user ADD CONSTRAINT progress_check
  CHECK (progress BETWEEN 0 AND 100 OR progress IS NULL);

------------------------ TRIGGERS ----------------------------

-- Set progress based on status
CREATE OR REPLACE FUNCTION set_progress_based_on_status()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'finished' THEN
        NEW.progress := 100;
    ELSIF NEW.status = 'reading' THEN
        IF NEW.progress >= 100 OR NEW.progress IS NULL THEN
            NEW.progress := 0;
        END IF;
    ELSIF NEW.status = 'want-to-read' THEN
        NEW.progress := 0;
    ELSE
        NEW.progress := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_progress ON book_user;
CREATE TRIGGER trg_set_progress
BEFORE INSERT OR UPDATE ON book_user
FOR EACH ROW
EXECUTE FUNCTION set_progress_based_on_status();

-- Calculate progress from page count and current page
CREATE OR REPLACE FUNCTION set_progress_from_pages()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.page_count IS NOT NULL AND NEW.current_page IS NOT NULL AND NEW.page_count > 0 THEN
        NEW.progress := ROUND(NEW.current_page * 100.0 / NEW.page_count);
    ELSIF NEW.status = 'reading' THEN
        NEW.progress := 0;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_progress_from_pages ON book_user;
CREATE TRIGGER trg_set_progress_from_pages
BEFORE INSERT OR UPDATE ON book_user
FOR EACH ROW
EXECUTE FUNCTION set_progress_from_pages();

-- Force set rating to NULL for 'want-to-read' status
CREATE OR REPLACE FUNCTION set_rating_null_for_want_to_read()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'want-to-read' THEN
        NEW.rating := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_rating_null ON book_user;
CREATE TRIGGER trg_set_rating_null
BEFORE INSERT OR UPDATE ON book_user
FOR EACH ROW
EXECUTE FUNCTION set_rating_null_for_want_to_read();

-- If book is finished, set current page to page count
CREATE OR REPLACE FUNCTION set_current_page_to_page_count()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'finished' AND NEW.page_count IS NOT NULL THEN
        NEW.current_page := NEW.page_count;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_current_page ON book_user;
CREATE TRIGGER trg_set_current_page
BEFORE INSERT OR UPDATE ON book_user
FOR EACH ROW
EXECUTE FUNCTION set_current_page_to_page_count();

-------------------- ROW LEVEL SECURITY ----------------------

ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE book_user ENABLE ROW LEVEL SECURITY;

------------------------ POLICIES ----------------------------

-- Books are public (can be shared across users)
CREATE POLICY "Anyone can view books" ON books
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert books" ON books
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Book-user relationships are private to each user
CREATE POLICY "Users can view own book relationships" ON book_user
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own book relationships" ON book_user
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own book relationships" ON book_user
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own book relationships" ON book_user
  FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Anyone can view demo user's books" ON book_user
  FOR SELECT USING (user_id = '00000000-0000-0000-0000-000000000000');


------------------------ SEED ----------------------------

-- insert a demo user
INSERT INTO auth.users (id, email) VALUES ('00000000-0000-0000-0000-000000000000', 'demo@example.com');

-- insert demo books
INSERT INTO public.books (title, author)
VALUES
  ('Emmaus', 'Alessandro Baricco'),
  ('Pride and Prejudice', 'Jane Austen'),
  ('1984', 'George Orwell'),
  ('War and Peace', 'Leo Tolstoy'),
  ('Klara and the Sun', 'Kazuo Ishiguro'),
  ('One Piece (Vol. 100)', 'Eiichiro Oda'),
  ('All about Love', 'bell hooks'),
  ('The Archaeology of knowledge', 'Michel Foucault'),
  ('The Plague', 'Albert Camus'),
  ('Metamorphosis', 'Franz Kafka'),
  ('Crime and Punishment', 'Fyodor Dostoevsky');

-- insert demo book-user relationships
INSERT INTO public.book_user (book_id, user_id, status, rating, page_count, current_page, comment)
VALUES
  ((SELECT id FROM public.books WHERE title = 'Emmaus' AND author = 'Alessandro Baricco'), '00000000-0000-0000-0000-000000000000', 'reading', 5, 150, 50, 'An amazing read! I didn''t expect it to become tragic at the end. I loved the relationship between the characters.'),
  ((SELECT id FROM public.books WHERE title = 'Pride and Prejudice' AND author = 'Jane Austen'), '00000000-0000-0000-0000-000000000000', 'want-to-read', NULL, 279, 0, 'Bought the book last year but still haven''t started it.'),
  ((SELECT id FROM public.books WHERE title = '1984' AND author = 'George Orwell'), '00000000-0000-0000-0000-000000000000', 'reading', 3, 250, 328, 'I thought I would like this one more.'),
  ((SELECT id FROM public.books WHERE title = 'War and Peace' AND author = 'Leo Tolstoy'), '00000000-0000-0000-0000-000000000000', 'finished', NULL, 1225, 1225, NULL),
  ((SELECT id FROM public.books WHERE title = 'Klara and the Sun' AND author = 'Kazuo Ishiguro'), '00000000-0000-0000-0000-000000000000', 'finished', 4, 320, 320, NULL),
  ((SELECT id FROM public.books WHERE title = 'One Piece (Vol. 100)' AND author = 'Eiichiro Oda'), '00000000-0000-0000-0000-000000000000', 'reading', NULL, 200, 40, NULL),
  ((SELECT id FROM public.books WHERE title = 'All about Love' AND author = 'bell hooks'), '00000000-0000-0000-0000-000000000000', 'want-to-read', NULL, NULL, NULL, 'Given to me in september'),
  ((SELECT id FROM public.books WHERE title = 'The Archaeology of knowledge' AND author = 'Michel Foucault'), '00000000-0000-0000-0000-000000000000', 'want-to-read', NULL, NULL, NULL, NULL),
  ((SELECT id FROM public.books WHERE title = 'The Plague' AND author = 'Albert Camus'), '00000000-0000-0000-0000-000000000000', 'reading', 4.0, 300, 150, 'quote from page 255 : “But, you know, I feel more fellowship with the defeated than with the saints. Heroism and sanctity don’t really appeal to me, I imagine. What interests me is being a man”'),
  ((SELECT id FROM public.books WHERE title = 'Metamorphosis' AND author = 'Franz Kafka'), '00000000-0000-0000-0000-000000000000', 'want-to-read', NULL, 100, 0, 'Recommended by Grace.'),
  ((SELECT id FROM public.books WHERE title = 'Crime and Punishment' AND author = 'Fyodor Dostoevsky'), '00000000-0000-0000-0000-000000000000', 'finished', NULL, 430, 430, NULL);
